[default]
address = "0.0.0.0"
port = 8000
log_level = "normal"
limits = { json = "2 MiB", data-form = "10 MiB" }

[default.shutdown]
ctrlc = true
signals = ["term"]
grace = 5
mercy = 5

[debug]
log_level = "debug"

[release]
log_level = "critical"
